export { default as Home } from './home'
export { default as Article } from './article'
export { default as Men } from './men'
export { default as Woman } from './woman'
export { default as Base } from './base'
export { default as Profile } from './profile'
