export const REGISTER = 'REGITER'
export const REGISTER_SUCCESS = 'REGITER_SUCCESS'
export const REGISTER_FAIL = 'REGITER_FAIL'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOG_OUT = 'LOG_OUT'

export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES'
export const GET_ALL_FAIL = 'GET_ALL_FAIL'

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL'
